services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: ["postgres", "-p", "1379"]
    ports:
      - "1379:1379"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 1379"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - shared_net

  api:
    build: ./cache_api
    restart: unless-stopped
    env_file:
      - ./cache_api/.env
    environment:
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./cache_api:/code
    networks:
      shared_net:
        aliases:
          - app-config

volumes:
  pgdata:

networks:
  shared_net:
    external: true